
name: Komunikacja Techniczna, Akademia Finansów i Biznesu Vistula
title: How to brew a coffee in AeroPress manual
description:  AeroPress and brewing description
remote_theme: KomunikacjaTechnicznaVistula/just-the-docs

color_scheme: vistula

# logo: "/assets/images/Morris_badge.png"

aux_links:
  "Source repository on GitHub":
    - "//github.com/KomunikacjaTechnicznaVistula/joanna-chodak"

back_to_top: true
back_to_top_text: "Back to top"

# footer_content: "</a>"