name: Komunikacja Techniczna, Akademia Finansów i Biznesu Vistula
title: How to brew a coffee in AeroPress manual
description: An example of technical documentation hosted on Github pages, using the Just the Docs Jekyll theme
remote_theme: KomunikacjaTechnicznaVistula/joanna-chodak

color_scheme: vistula



aux_links:
  "Source repository on GitHub":
    - "//github.com/KomunikacjaTechnicznaVistula/joanna-chodak"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "This documentation is part of the reference materials for the Technical Communication course at Vistula University (Warsaw). The content is based on <a href=\"https://github.com/flicstar/DITA-Mini-Manual\">Felicity Brand's example DITA project.</a>"